services:
  # Rust Server
  server:
    build: .
    container_name: community_coin_server
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5433/community_coin_db
      - REDIS_URL=redis://localhost:6380
      - SOLANA_RPC_URL=https://localhost:8899
      - SOLANA_WS_URL=wss://localhost:8899
      - COMMCOIN_PROGRAM_ID=your_commcoin_program_id_here
      - JWT_SECRET=your_jwt_secret_here_make_it_long_and_secure
      - SUPABASE_URL=https://your-project.supabase.co
      - SUPABASE_ANON_KEY=your_supabase_anon_key
      - SUPABASE_SERVICE_KEY=your_supabase_service_key
      - PORT=8080
      - ENVIRONMENT=development
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prometheus for metrics

volumes:
  postgres_data:
  redis_data: